config/routes.rb
Rails.application.routes.draw do
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  resources :subscribers
  resources :posts

  root "home#index"

  get 'disclosures' => 'home#disclosures', as: 'disclosures'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  has_one_attached :image

  has_many :post_topics
  has_many :topics, through: :post_topics

  scope :published, -> { where(is_published: true) }

  validates :title, presence: true
  validates :date, presence: true

  has_rich_text :content

  after_initialize :init

  def init
    self.date ||= Date.today
    self.author ||= Rails.configuration&.default_author || nil
  end
end

app/models/post_topic.rb
class PostTopic < ApplicationRecord
  belongs_to :post
  belongs_to :topic
end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
end

app/models/topic.rb
class Topic < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.published.order(date: :desc)
  end

  def disclosures
    @title = 'Disclosures | Thinking Money | NUKU'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_login, except: [:show]
  before_action :set_post, only: %i[ show edit update destroy ]

  def index
    @posts = Post.all
  end

  def show
    @title = @post.title + ' | Thinking Money'
    @topics = @post.topics
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to post_url(@post), notice: "Post was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @post.update(post_params)
      redirect_to post_url(@post), notice: "Post was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post.destroy

    redirect_to posts_url, notice: "Post was successfully destroyed."
  end

  private
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :author, :date, :is_published, :content, :image)
    end
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  before_action :require_login, except: [:new, :create]
  before_action :set_subscriber, only: %i[ show edit update destroy ]

  # GET /subscribers or /subscribers.json
  def index
    @subscribers = Subscriber.all
  end

  # GET /subscribers/new
  def new
    @subscriber = Subscriber.new
    @title = 'Subscribe to Thinking Money | NUKU'
  end

  # POST /subscribers or /subscribers.json
  def create
    @subscriber = Subscriber.new(subscriber_params)

    if @subscriber.save
      redirect_to root_path, notice: "You have been subscribed."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /subscribers/1 or /subscribers/1.json
  def update
    respond_to do |format|
      if @subscriber.update(subscriber_params)
        format.html { redirect_to subscriber_url(@subscriber), notice: "Subscriber was successfully updated." }
        format.json { render :show, status: :ok, location: @subscriber }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @subscriber.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscribers/1 or /subscribers/1.json
  def destroy
    @subscriber.destroy

    respond_to do |format|
      format.html { redirect_to subscribers_url, notice: "Subscriber was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscriber
      @subscriber = Subscriber.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def subscriber_params
      params.require(:subscriber).permit(:email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/application/_banner.html.haml
#banner
  %h1 Thinking Money
  %h2 A NUKU Blog by Carson Cole

.clear-bar

app/views/application/_flash.html.haml
#flash
  - flash.each do |key, value|
    .container
      .row
        .col-md-6
          .flash
            = value

app/views/application/_footer.html.haml
%footer.d-print-none
  .container
    = link_to "NUKU.com", 'https://nuku.com'
    \|
    = link_to "Subscribe", new_subscriber_path
    \|
    = link_to "Disclosures", disclosures_path
    \|
    = link_to "Privacy", "https://nuku.com/privacy-policy", target: '_blank'
    \|
    .small
      Copyright ©
      = Date.today.year
      NUKU Inc. All rights reserved.

app/views/application/_google_tag_manager_body.html.erb
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=<%= Rails.application.credentials.dig(:google_tag_manager_id) %>"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->

app/views/application/_google_tag_manager_head.html.erb
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer',"<%= Rails.application.credentials.dig(:google_tag_manager_id) %>");</script>
<!-- End Google Tag Manager -->

app/views/application/_head.html.haml
%head
  = render 'google_tag_manager_head' if Rails.env.production?
  = render 'meta'
  = csrf_meta_tags
  = csp_meta_tag

  = stylesheet_link_tag "application", "data-turbo-track": "reload"
  = javascript_importmap_tags
  = javascript_include_tag 'application'

app/views/application/_header.html.haml
%nav.navbar.navbar-expand-lg.navbar-dark.main-navbar.d-print-none
  .container-fluid
    = link_to image_tag("logo.png", height: "15px", alt: 'NUKU Logo'), root_path, class: 'navbar-brand'
    %button.navbar-toggler(type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation")
      %span.navbar-toggler-icon
    - if signed_in?
      %div
        = link_to "New Post", new_post_path
        \|
        = link_to "Posts", posts_path

      = button_to "Sign out", sign_out_path, method: :delete, class: 'btn btn-sm btn-primary'

app/views/application/_meta.html.haml
%title= @title || Rails.configuration&.application_title
%meta(name="viewport" content="width=device-width,initial-scale=1")
%meta{name: "description", content: Rails.configuration.application_description}

%link(rel="canonical" href="#{url_for(:only_path => false, :protocol => 'https')}")

<!-- Google / Search Engine Tags -->
%meta{itemprop: "name", content: Rails.configuration&.application_title}
%meta{itemprop: "description", content: Rails.configuration.application_description}
/ %meta{itemprop: "image", content: Rails.configuration.application_image_url}

<!-- Facebook Meta Tags -->
%meta{property: "og:url", content: "https://blog.nuku.com"}
%meta{property: "og:type", content: "website"}
%meta{property: "og:title", content: Rails.configuration&.application_title}
%meta{property: "og:description", content: Rails.configuration.application_description}
/ %meta{property: "og:image", content: Rails.configuration.application_image_url}

<!-- Twitter Meta Tags -->
%meta{name: "twitter:card", content: "summary_large_image"}
%meta{name: "twitter:title", content: Rails.configuration&.application_title}
%meta{name: "twitter:description", content: Rails.configuration.application_description}
/ %meta{name: "twitter:image", content: Rails.configuration.application_image_url}

app/views/home/disclosures.html.haml
#disclosures

  %h1 Disclosures

  %br

  %p The NUKU Blog reflects the personal opinions, viewpoints and analyses of Carson Cole, and should not be regarded as a description of the advisory services or investment returns provided by NUKU Asset.

  %p The views reflected in the commentary are subject to change at any time without notice. Nothing on this website constitutes investment advice, performance data or any recommendation that any particular security, portfolio of securities, transaction or investment strategy is suitable for any specific person.

  %p Any mention of a particular security and related performance data is not a recommendation to buy or sell that security. NUKU Asset manages its clients’ accounts using a variety of investment techniques and strategies, which are not necessarily discussed in the commentary. Investments in securities involve the risk of loss. Past performance is no guarantee of future results.

app/views/home/index.html.haml
#articles
  = render @posts

app/views/home/privacy.html.haml
#privacy
  %h1 Privacy Policy

  %p NUKU does not disclose the personal or business information of its clients and website users to any other person, except as required to perform administrative or account servicing tasks (such as those provided by trustees, prime brokers or broker-dealers), and secures client information, whether in paper or electronic form, limiting access only to authorized persons.

  %p The information NUKU collects is not shared with or sold to other organizations for commercial purposes, except to provide products or services you've requested, when we have your permission, or under the following circumstances: it is necessary to share information in order to investigate, prevent, or take action regarding illegal activities, suspected fraud, situations involving potential threats to the physical safety of any person, violations of Terms of Use, or as otherwise required by law.

  %h2 Security
  %p The security of your information is important to us and we take our responsibility as a custodian of that information very seriously. All communications through our website are conducted through SSL, which is a form of encrypted communication. The url of our site will show “https” and in some browsers will show a symbol indicating that the connection is secure. We also encrypt your service password so that your password cannot be recovered, even by us.

  %p Please note that you are responsible for maintaining the confidentiality of your login ID and password, and that in order to ensure the security of your information and / or account, we will never ask you for your login password.

  %h2 Cookies
  %p A cookie is a small amount of data, which often includes an anonymous unique identifier, that is sent to your browser from a web site’s computers and stored on your computer’s hard drive.

  %p Cookies are required to use NUKU’s services.

  %p We use cookies to record current session information, but do not use permanent cookies. You are required to re-login to your NUKU account after a certain period of time has elapsed to protect you against others accidentally accessing your account contents.

  %h2 Changes
  %p NUKU may periodically update this policy. We will notify you about significant changes in the way we treat personal information by sending a notice to the primary email address specified in your NUKU account or by placing a prominent notice on our site.

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.haml
!!!
%html
  = render 'head'
  %body
    = render 'google_tag_manager_body' if Rails.env.production?
    = render 'header'
    = render 'banner' if controller_name == 'home'
    = render 'flash' unless flash.empty?
    #content
      .container
        = yield
    = render 'footer'

app/views/posts/_form.html.haml
= form_for @post do |f|
  - if @post.errors.any?
    #error_explanation
      %h2= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      %ul
        - @post.errors.full_messages.each do |message|
          %li= message

  .row
    .col-md-5
      .mb-3
        = f.label :title, class: 'form-label'
        = f.text_field :title, class: 'form-control'
  .row
    .col-md-10
      .mb-3
        = f.label :content
        = f.rich_text_area :content, class: 'form-control'
  .row
    .col-md-5
      .mb-3
        = f.label :author, class: 'form-label'
        = f.text_field :author, class: 'form-control'
  .row
    .col-md-5
      .mb-3
        = f.label :date, class: 'form-label'
        = f.date_field :date
  .row
    .col-md-5
      .mb-3
        = f.label :image, class: 'form-label'
        = f.file_field :image
  .row
    .col-md-5
      .mb-3
        = f.check_box :is_published, class: 'form-check-button'
        = f.label :is_published, class: 'form-check-label'
  .actions
    = f.submit 'Save', class: 'btn btn-primary'

app/views/posts/_post.html.haml
%article
  .row
    .col-md-7
      %h1= link_to post.title, post

      %p
        = post.content.to_plain_text.truncate(400)
        = link_to "Continue reading", post, class: 'read-more'

      %p.date
        - if post.date.year < Date.today.year
          = post.date.strftime("%B %e, %Y")
        - else
          = post.date.strftime("%b %e")

      = render post.topics

    .col-md-1
    .col-md-4
      - if post.image.attached? && post.image.representable?
        = image_tag post.image.representation(resize_to_limit: [320, nil]), class: 'img-fluid'

app/views/posts/edit.html.haml
%h1 Editing post

= render 'form'

app/views/posts/index.html.haml
%h1 Posts

%table.table
  %thead
    %tr
      %th Title

      %th Author
      %th Date
      %th Is published
      %th
      %th
      %th

  %tbody
    - @posts.each do |post|
      %tr
        %td= post.title
        %td= post.author
        %td= post.date
        %td= post.is_published
        %td= link_to 'Show', post
        %td= link_to 'Edit', edit_post_path(post)
        %td= link_to 'Destroy', post, data: { "turbo-method": :delete, confirm: 'Are you sure?' }

%br

= link_to 'New Post', new_post_path

app/views/posts/new.html.haml
%h1 New post

= render 'form'

app/views/posts/show.html.haml
#post
  %article
    .row
      .col-md-12
        %h1= @post.title

    .row
      .col-md-7

        %p= @post.content


        %br
        %p.author= @post.author
        .date.small= @post.date.strftime("%B %d, %Y")
        - if signed_in?
          %p= link_to "Edit", edit_post_path(@post)

      .col-md-1
      .col-md-4
        / - if @post.image.attached? && @post.image.representable?
        /   .text-center
        /     = image_tag @post.image.representation(resize_to_limit: [500, nil]), class: 'img-fluid'

        %br
        / .text-center
        /   = link_to "Subscribe", new_subscriber_path, class: 'subscribe-link'


    .row
      .col-md-12
        = render @topics


.row.d-print-none
  .col-md-5
    %p= link_to "All Posts", root_path

app/views/subscribers/_form.html.haml
= form_for @subscriber do |f|
  - if @subscriber.errors.any?
    #error_explanation
      %h2= "#{pluralize(@subscriber.errors.count, "error")} prohibited this subscriber from being saved:"
      %ul
        - @subscriber.errors.full_messages.each do |message|
          %li= message

  = f.label :email, class: 'form-label'
  = f.email_field :email, class: 'form-control'

  %br
  = f.submit 'Subscribe', class: 'btn btn-primary'

app/views/subscribers/index.html.haml
%h1 Listing subscribers

%table
  %thead
    %tr
      %th Email
      %th
      %th
      %th

  %tbody
    - @subscribers.each do |subscriber|
      %tr
        %td= subscriber.email
        %td= link_to 'Show', subscriber
        %td= link_to 'Edit', edit_subscriber_path(subscriber)
        %td= link_to 'Destroy', subscriber, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Subscriber', new_subscriber_path

app/views/subscribers/new.html.haml
#subscribe

  .row
    .col-md-12
      %h1 Subscribe
  .row
    .col-md-5
      = render 'form'

app/views/subscribers/show.html.haml
%p#notice= notice

%p
  %b Email:
  = @subscriber.email

= link_to 'Edit', edit_subscriber_path(@subscriber)
\|
= link_to 'Back', subscribers_path

app/views/topics/_topic.html.haml
.topic= topic.name

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>